### ISSUE TITLE
Apply simple Tractor-style Gaussian priors on model parameters

### ISSUE THREAD

**Issue by aagnello** [davidwhogg/LensTractor#46]
Leaving all the parameters free to wander is useless and dangerous, sometimes LT crashes (through emcee or the optimizer) on problems where it shouldn't. I'd lie the following priors to be implemented, but I don't know how to code that:
 -- guess values for the fluxes should be started around the linear solution;
 -- the galaxy's effective radius cannot be smaller than one pixel or so, otherwise it's
 effectively a point source!
 -- the "galaxy" cannot be fainter than, say, i-band=22, otherwise LT can use a faint "galaxy" to cover residuals from a bad fit;
 -- for the same reasons, the galaxy's axis ratio cannot be smaller than say 0.3;
 -- I'd like a **shallow**(!) penalty term for positions that are too far from the centroid, so that they cannot wander too much around the cutout.

**Comment by drphilmarshall** [comment]
Hey @dstndstn! Something is broken in the Tractor, I think. Try this, from your LensTractor directory:

    mkdir -p priortest ; cd priortest
    python ../LensTractor.py -n 4 -z -v --survey PS1 --manual ../examples/ps1/H1413+117_10x10arcsec_Nebula4_init.txt -o H1413+117_10x10arcsec ../examples/ps1/H1413+117_10x10arcsec_*.fits 

You should get the following error:

    Traceback (most recent call last):
    File "../LensTractor.py", line 319, in main
    LT = lenstractor.LensTractor(dataset,model,args.outstem,args.survey,counter=counter,vb=vb,noplots=args.noplots)
    File "/Users/pjm/work/stronglensing/LensTractor/lenstractor/driver.py", line 98, in __init__
      self.plot_state('progress-%02d_initial_'%self.counter+self.model.name)
    File "/Users/pjm/work/stronglensing/LensTractor/lenstractor/driver.py", line 517, in plot_state
      chi = self.chug.getChiImage(i)
    File "/Users/pjm/work/tractor/tractor/engine.py", line 2424, in getChiImage
      mod = self.getModelImage(img, srcs=srcs, minsb=minsb)
    File "/Users/pjm/work/tractor/tractor/engine.py", line 2304, in getModelImage
      patch = self.getModelPatch(img, src, minsb=minsb)
    File "/Users/pjm/work/tractor/tractor/engine.py", line 2283, in getModelPatch
      mod = self.getModelPatchNoCache(img, src, minsb=minsb, **kwargs)
    File "/Users/pjm/work/tractor/tractor/engine.py", line 2266, in getModelPatchNoCache
      return src.getModelPatch(img, **kwargs)
    File "/Users/pjm/work/tractor/tractor/galaxy.py", line 148, in getModelPatch
      p1 = self.getUnitFluxModelPatch(img, minval=minval)
    File "/Users/pjm/work/tractor/tractor/galaxy.py", line 313, in getUnitFluxModelPatch
      extent=extent)
    File "/Users/pjm/work/tractor/tractor/galaxy.py", line 362, in _realGetUnitFluxModelPatch
      exactExtent=(extent is not None))
    File "/Users/pjm/work/tractor/tractor/mixture_profiles.py", line 350, in mixture_to_patch
      return mixture.evaluate_grid(x0, x1, y0, y1, 0., 0.)
    File "/Users/pjm/work/tractor/tractor/mixture_profiles.py", line 237, in evaluate_grid_dstn
      self.amp, self.mean,self.var, result)
  TypeError: in method 'c_gauss_2d_grid', argument 6 of type 'int'

I'll check the Tractor issues for this function call.

**Comment by drphilmarshall** [comment]
Still to do apart from @dstndstn 's bug fix:

* [ ] Gaussian priors on Nebula point sources
* [ ] Gaussian priors on Lens Galaxy (can this now inherit from Nebula Galaxy?!)
* [ ] Gaussian priors on Lens Point Source

This might need us to create either a subclass LTPointSource so that we can add priors to it, or a function that adds Gaussian priors to our PointSource objects.

**Comment by drphilmarshall** [comment]
PS. @dstndstn writes (offline): 
"Did you try re-"make"ing in the tractor directory?  I just hit this myself in an old installation."  

This does indeed fix this problem. Thanks Dustin!
